version: '3.8'  # Версия Docker Compose

services:
  app:  # Название сервиса
    build:
    # Контекст для сборки образа,
    # в данном случае, текущая директория
      context: .
    # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
    image: kima30/docker-project-74:latest # Для использования из Docker Hub
    volumes:
    - ./app:/app # Монтируем локальную директорию app в контейнер
    - /app/node_modules
    # ports:
    #  - "8080:8080"  # Пробрасываем порты
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:  