version: '3.8'  # Версия Docker Compose

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production # Используем Dockerfile.production для тестов
    # command: make test  # Указываем команду, которая будет выполнена при запуске
    command: ${COMMAND:-make dev}  # По умолчанию make dev, но можно переопределить
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"  # Пробрасываем порты
    volumes:
    - ./app:/app  # Монтируем локальную директорию app в контейнер
    - /app/node_modules