version: '3.8'  # Версия Docker Compose

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production # Используем Dockerfile.production для тестов
    # command: make test  # Указываем команду, которая будет выполнена при запуске
    command: ${COMMAND:-make dev}  # По умолчанию make dev, но можно переопределить
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:8080"  # Пробрасываем порты
    volumes:
    - ./app:/app  # Монтируем локальную директорию app в контейнер
    - /app/node_modules